USE clientes;
CREATE TABLE ListaClientes(
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
telefone VARCHAR(100) NOT NULL,
data_nascimento DATE NOT NULL
);




